//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR67_VP.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalServices> AdditionalServices { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ConstructionMaterials> ConstructionMaterials { get; set; }
        public virtual DbSet<ConstructionPhases> ConstructionPhases { get; set; }
        public virtual DbSet<DesignerServices> DesignerServices { get; set; }
        public virtual DbSet<FinancialData> FinancialData { get; set; }
        public virtual DbSet<FinishingMaterials> FinishingMaterials { get; set; }
        public virtual DbSet<MaterialBatches> MaterialBatches { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SecurityServices> SecurityServices { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
    }
}
