//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR67_VP.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objects()
        {
            this.AdditionalServices = new HashSet<AdditionalServices>();
            this.ConstructionPhases = new HashSet<ConstructionPhases>();
            this.DesignerServices = new HashSet<DesignerServices>();
            this.FinancialData = new HashSet<FinancialData>();
            this.SecurityServices = new HashSet<SecurityServices>();
            this.Workers = new HashSet<Workers>();
        }
    
        public int ID_Object { get; set; }
        public int ID_Order { get; set; }
        public int ID_ConstMaterial { get; set; }
        public int ID_FinMAterial { get; set; }
        public string NameObject { get; set; }
        public string FoundationStatus { get; set; }
        public string FrameStatus { get; set; }
        public string RoofStatus { get; set; }
        public string InteriorStatus { get; set; }
        public string TechnicalControlStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalServices> AdditionalServices { get; set; }
        public virtual ConstructionMaterials ConstructionMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionPhases> ConstructionPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesignerServices> DesignerServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialData> FinancialData { get; set; }
        public virtual FinishingMaterials FinishingMaterials { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityServices> SecurityServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
