//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace PR67_VP.model
{
    public partial class Workers
    {
        public int ID_Worker { get; set; }
        public Nullable<int> ID_Object { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public string WorkerName { get; set; }
        public string WorkerSurname { get; set; }
        public string WorkerPatronymic { get; set; }
        public string phoneNumber { get; set; }
        public string w_login { get; set; }
        public string w_pswd { get; set; }
        public Nullable<int> ID_Gender { get; set; }

        public virtual Objects Objects { get; set; }
        public virtual Role Role { get; set; }
        public virtual Gender Gender { get; set; }

        // Валидации для формы AddWorkers
        public class AddWorkersValidation
        {
            [Required(ErrorMessage = "Имя работника является обязательным полем.")]
            [StringLength(50, MinimumLength = 3, ErrorMessage = "Имя работника должно быть от 3 до 50 символов.")]
            public string WorkerName { get; set; }

            [Required(ErrorMessage = "Фамилия работника является обязательным полем.")]
            [StringLength(50, MinimumLength = 3, ErrorMessage = "Фамилия работника должна быть от 3 до 50 символов.")]
            public string WorkerSurname { get; set; }

            public string WorkerPatronymic { get; set; } // Необязательное поле

            [Required(ErrorMessage = "Номер телефона является обязательным полем.")]
            [RegularExpression(@"^(\+7|8)[0-9]{10}$", ErrorMessage = "Неверный формат номера телефона. Номер должен начинаться с +7 или 8 и содержать ровно 11 цифр.")]
            public string phoneNumber { get; set; }

            [Required(ErrorMessage = "Логин является обязательным полем.")]
            [StringLength(20, MinimumLength = 4, ErrorMessage = "Логин должен содержать от 4 до 20 символов.")]
            [RegularExpression(@"^[\w-]+$", ErrorMessage = "Логин должен содержать только буквы, цифры и символы: _, -")]
            public string w_login { get; set; }

            [Required(ErrorMessage = "Пароль является обязательным полем.")]
            public string w_pswd { get; set; }
        }

        // Валидации для формы EditWorkers
        public class EditWorkersValidation
        {
            [Required(ErrorMessage = "Имя сотрудника обязательно для заполнения.")]
            [StringLength(50, MinimumLength = 3, ErrorMessage = "Имя сотрудника должно быть от 3 до 50 символов.")]
            public string WorkerName { get; set; }

            [Required(ErrorMessage = "Фамилия работника является обязательным полем.")]
            [StringLength(50, MinimumLength = 3, ErrorMessage = "Фамилия работника должна быть от 3 до 50 символов.")]
            public string WorkerSurname { get; set; }

            public string WorkerPatronymic { get; set; } // Необязательное поле

            [Required(ErrorMessage = "Номер телефона является обязательным полем.")]
            [RegularExpression(@"^(\+7|8)[0-9]{10}$", ErrorMessage = "Неверный формат номера телефона. Номер должен начинаться с +7 или 8 и содержать ровно 11 цифр.")]
            public string phoneNumber { get; set; }

            [Required(ErrorMessage = "Логин является обязательным полем.")]
            [StringLength(20, MinimumLength = 4, ErrorMessage = "Логин должен содержать от 4 до 20 символов.")]
            [RegularExpression(@"^[\w-]+$", ErrorMessage = "Логин должен содержать только буквы, цифры и символы: _, -")]
            public string w_login { get; set; }

            public string w_pswd { get; set; } // Пароль, не проверяем в данном контексте
        }
    }
}

